services:
  - type: web
    name: don-onofre-adamspay
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
    startCommand: gunicorn dononofre.wsgi