services:
  - type: web
    name: don-onofre-adamspay
    env: python
    buildCommand: ./build.sh
    startCommand: |
      echo "=== EXECUTANDO STARTUP SCRIPT ===" &&
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn dononofre.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://dononofredb_user:ZWZ2GNPDnJRkN607xUINJ2jPL4drwXZW@dpg-d5t7p8chg0os73a4idq0-a/dononofredb
      - key: RENDER
        value: true
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000